define('dashboard/microAppsUrlMapper',{
    // PLEASE SEE FOR DOCUMENTATION:
    // `test/dashboard/js/lib/mapper/microAppsUrl.js`
    definitions: {
        default: 'header.index,menu.index',
        defaultWithFlyout: 'default,flyout.index',
        defaultWithMyHome: 'myHome.chaseMyHome.index,header.index,menu.index',
        defaultWithInvestmentsFooter: 'header.index,flyout.index,menu.ignore,shared.index,investmentDisclosure.investmentsFooter',
        defaultWithMenuIgnore: 'menu.ignore,header.index,shared.index,flyout.index',
        defaultWithoutHeaderIndex: 'menu.ignore,shared.index,flyout.index',
        defaultWithCJP: 'menu.index,header.index,shared.index,creditJourney.container.octagonRoute'
    },
    mapper: {
        default: [
            'aggregation',
            'underwriting',
            'homeLendingPayments',
            'cardLendingPayments',
            'investmentProspect',
            'merchantPreference',
            'myrealestate',
            'oi-portfolio',
            'oi-trade',
            'payinfour',
            'reporting',
            'retirementHub',
            'retirementPlanningCalculators',
            'retirementhealthcare',
            'screeners',
            'spendingPlanner',
            'autosave',
            'storefront',
            'summary',
            'activity',
            'imageDetails',
            'transactionDetails',
            'securityandprivacy',
            'chaseonboarding',
            'helpandsupport',
            'travel',
            'dining.zagatsurvey',
            'dining.dininghub',
            'lifestyle.experiences',
            'vterminal',
            'appointments',
            'accounting',
            'myAdvisoryTeam',
            'emob',
            'emobchecklist',
            'chaseexperience',
            'transfersecurities',
            'autoLendingServicing',
            'acceptCardPayments',
            'merchant-fees',
            'merchantOffers',
            'merchantWalletProvisioning',
            'paypalpullprovisioning',
            'paymentplanrecovery',
            'smbinvoicing',
            'collectanddeposithub',
            'shoppingplatform',
            'estatebeneficiary',
            'benefits',
            'consumerinsights',
            'campaignmanager',
            'realtimerequestpayment',
            'realtimerequestpaymentactivity',
            'smbcatalog',
            'payroll',
            'wires.sendmoney',
            'wires.adddomesticrecipient',
            'wires.addinternationalrecipient',
            'wires.managerecipient',
            'wires.editrecipient',
            'wires.enrolldevice',
            'wires.managerecipienthub',
            'wires.managetransaction',
            'overdraftservices',
            'depositservicing',
            'shopping',
            'fraudsecurityhub',
            'quickaccept',
            'billpaydirectory',
            'snapshot',
            'profilesettings',
            'demographics',
            'prospectDashboard',
            'merchantpayment',
            'acceptCardPayments',
            'cardtracker',
            'cardactivation',
            'activityreportui',
            'offertracker',
            'redeemcoupon',
            'pcr',
            'sendbusinesspayments',
            'balance-transfers',
            'auto',
            'setprimaryaccount',
            'slatetracker',
            'claimsanddisputes',
            'periodicinvesting',
            'autolendingpayments',
            'business-loans',
            'requestInfo',
            'activity',
            'qdenrollment',
            'p2pRequestMoney',
            'dividendsAndCapitalGains',
            'fullyPaidLending',
            'thirdpartyconsentservices',
            'cardreplacement',
            'mydocs',
            'trackerhub'
        ],
        defaultWithFlyout: [
            'businessQuarterlyReport',
            'externalAccountSummary',
            'externalAccountDashboard',
            'findinvestments.overview',
            'interstitialmicroapp',
            'investmentProspect',
            'investmentSearchResults',
            'myrealestate',
            'oi-portfolio',
            'oi-trade',
            'retirementHub',
            'retirementPlanningCalculators',
            'retirementRollover',
            'retirementhealthcare',
            'screeners',
            'activity',
            'transactions',
            'summary',
            'myAdvisoryTeam',
            'emob',
            'emobchecklist',
            'chaseexperience',
            'benefits',
            'acp-onboarding',
            'merchant-fees',
            'investmentcheckup',
            'realtimerequestpayment',
            'realtimerequestpaymentactivity',
            'payovertime',
            'slatetracker',
            'selfServiceReversal',
            'activityDetailsReversal',
            'requestInfo',
            'collectanddeposithub',
            'cardreplacement',
            'mydocs'
        ],
        defaultWithMyHome: [
            'cmh',
            'myhomecalculators',
            'myhomeoffers',
            'myhomerates',
            'cmhbuy',
            'cmhinsights',
            'cmhdashboard'
        ],
        defaultWithInvestmentsFooter: [
            'cevm'
        ],
        defaultWithMenuIgnore: [
            'idlecash',
            'oi-agreements',
            'accountfundinghub',
            'managetransfer',
            'advisorservices.overview',
            'personaladvisor.overview',
            'privateclientadvisors.overview',
            'selfdirectedinvesting.overview',
            'whatwedo.overview',
            'productfinderquiz.investment',
            'overview',
            'marketcontainer',
            'explore'
        ],
        defaultWithoutHeaderIndex: [
            'underwriting'
        ],
        defaultWithCJP: [
            'creditjourneyapp'
        ]
    },
});


define("dashboard/microAppsUrlMapper", [],function(){});
