steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/compass-outlaw:$COMMIT_SHA', '.']
  
  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/compass-outlaw:$COMMIT_SHA']

  # Deploy container image to Cloud Run (Optimized)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'compass-outlaw'
      - '--image'
      - 'gcr.io/$PROJECT_ID/compass-outlaw:$COMMIT_SHA'
      - '--region'
      - 'us-west2'
      - '--platform'
      - 'managed'
      - '--service-account'
      - 'compass-outlaw@agency-fortress-core-479708.iam.gserviceaccount.com'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/compass-outlaw:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY