name: Bug Report
description: Report a bug or issue
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        ## Bug Report
        Thank you for reporting a bug!
        
  - type: input
    id: epic-ref
    attributes:
      label: Related Epic
      description: "If this relates to an Epic, reference it here (e.g., #1)"
      placeholder: "Refers to Epic #"

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: What is the bug?
      placeholder: "A clear and concise description of the bug..."
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: "Describe what you expected to happen..."
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: "Describe what actually happens..."
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: What environment are you using?
      placeholder: |
        - OS: [e.g., macOS, Windows, Linux]
        - Browser: [e.g., Chrome, Firefox]
        - Version: [e.g., 1.0.0]
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: What is the severity?
      options:
        - "Critical"
        - "High"
        - "Medium"
        - "Low"
      default: 2

  - type: textarea
    id: logs
    attributes:
      label: Logs/Screenshots
      description: Add any relevant logs, error messages, or screenshots

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context about the problem
